#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UserAwards;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Person/Index.cshtml")]
    public partial class _Views_Person_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<UserAwards.Models.PersonModel>>
    {
        public _Views_Person_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Person\Index.cshtml"
  
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_LayoutPerson.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\tfunction Refresh() {\r\n\t\t$.ajax({\r\n\t\t\turl: \'");

            
            #line 13 "..\..\Views\Person\Index.cshtml"
             Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\tmrthod: \"GET\",\r\n\t\t\tsuccess: function(data) {\r\n\t\t\t\t$(\'#personList\').html(da" +
"ta);\r\n\t\t\t}\r\n\t\t});\r\n\t}\r\n\r\n\tfunction ConfirmChange() {\r\n\t\t$.ajax({\r\n\t\t\turl: \'");

            
            #line 23 "..\..\Views\Person\Index.cshtml"
             Write(Url.Action("ConfirmListCreate"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\tmrthod: \"GET\",\r\n\t\t\tsuccess: function(data) {\r\n\t\t\t\t$(\'#personList\').html(da" +
"ta);\r\n\t\t\t}\r\n\t\t});\r\n\t};\r\n\r\n\tfunction RevertChange() {\r\n\t\t$.ajax({\r\n\t\t\turl: \'");

            
            #line 33 "..\..\Views\Person\Index.cshtml"
             Write(Url.Action("RevertListCreate"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n\t\t\tmrthod: \"GET\",\r\n\t\t\tsuccess: function(data) {\r\n\t\t\t\t$(\'#personList\').html(da" +
"ta);\r\n\t\t\t}\r\n\t\t});\r\n\t};\r\n\r\n</script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
	$(document).ready(function () {
		$(function () {
			$('#ShowCreatePersonWindow').on('click', function () {
					var url = ""/Person/TemplateCreateNewPersonPartial/"";
					$.post(url)
						.done(function(response) {
							$(""#CreatePersonWindow"").html(response);
							$('#CreatePersonWindow .modal').modal({});
						})
						.fail(function() {
							alert(""error"");
						});
				});
		});
	});

	function OnDeletePerson(data, status, request) {
		alert(""OnDeletePerson"");
		if (data.error) {
			OnError(request, status, data.error);
			return;
		}
		alert(test);
		$('#personList').html(data);
	}

	function OnError(request, status, error) {
		alert(error);
	}
</script>

<p>
");

WriteLiteral("\t");

            
            #line 76 "..\..\Views\Person\Index.cshtml"
Write(Html.ActionLink("Get list person", "GetListPerson"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n\r\n<div");

WriteLiteral(" id=\"CreatePersonWindow\"");

WriteLiteral(">\r\n</div>\r\n\r\n<p>\r\n");

WriteLiteral("\t");

            
            #line 84 "..\..\Views\Person\Index.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n\r\n<div>\r\n\t<button");

WriteLiteral(" id=\"Confirm\"");

WriteLiteral(" onclick=ConfirmChange()");

WriteLiteral(">Confirm change</button>\r\n\t<button");

WriteLiteral(" id=\"Revert\"");

WriteLiteral(" onclick=RevertChange()");

WriteLiteral(">Revert change</button>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"personList\"");

WriteLiteral(">\r\n");

            
            #line 93 "..\..\Views\Person\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 93 "..\..\Views\Person\Index.cshtml"
       Html.RenderPartial("_IndexListPartial"); 
            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<p>\r\n\t<a");

WriteLiteral(" id=\"ShowCreatePersonWindow\"");

WriteLiteral(">Add new person for AJAX</a>\r\n</p>\r\n\r\n<p>\r\n\t<a");

WriteLiteral(" onclick=\"Refresh()\"");

WriteLiteral(">Refresh for AJAX</a>\r\n</p>");

        }
    }
}
#pragma warning restore 1591
