#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using UserAwards;
    
    #line 1 "..\..\Views\Award\Index.cshtml"
    using UserAwards.Models.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Award/Index.cshtml")]
    public partial class _Views_Award_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<UserAwards.Models.AwardModel>>
    {
        public _Views_Award_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Award\Index.cshtml"
  
	ViewBag.Title = "Index";
	Layout = "~/Views/Shared/_LayoutAward.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>Index</h2>\r\n\r\n<p>\r\n");

WriteLiteral("\t");

            
            #line 12 "..\..\Views\Award\Index.cshtml"
Write(Html.ActionLink("Create New", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n<table>\r\n\t<tr>\r\n\t\t<th>\r\n");

WriteLiteral("\t\t\t");

            
            #line 17 "..\..\Views\Award\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.ImageData));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</th>\r\n\t\t<th>\r\n");

WriteLiteral("\t\t\t");

            
            #line 20 "..\..\Views\Award\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</th>\r\n\t\t<th>\r\n");

WriteLiteral("\t\t\t");

            
            #line 23 "..\..\Views\Award\Index.cshtml"
       Write(Html.DisplayNameFor(model => model.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t</th>\r\n\t\t<th></th>\r\n\t</tr>\r\n\r\n");

            
            #line 28 "..\..\Views\Award\Index.cshtml"
	
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Award\Index.cshtml"
     foreach (var item in Model)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<tr>\r\n\t\t\t<td>\r\n\t\t\t\t<img");

WriteLiteral(" class=\"img-thumbnail\"");

WriteLiteral(" width=\"30\"");

WriteLiteral(" height=\"30\"");

WriteAttribute("src", Tuple.Create("\r\n\t\t\t\t\t src=\"", 589), Tuple.Create("\"", 649)
            
            #line 33 "..\..\Views\Award\Index.cshtml"
, Tuple.Create(Tuple.Create("", 602), Tuple.Create<System.Object, System.Int32>(Url.Action("GetImage", "Award", new {item.Id})
            
            #line default
            #line hidden
, 602), false)
);

WriteLiteral(" />\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 36 "..\..\Views\Award\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 39 "..\..\Views\Award\Index.cshtml"
           Write(Html.DisplayFor(modelItem => item.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t\t<td>\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 42 "..\..\Views\Award\Index.cshtml"
           Write(Html.ActionLink("Edit", "Edit", new {id = item.Id}));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 43 "..\..\Views\Award\Index.cshtml"
           Write(Html.ActionLink("Details", "Details", new {id = item.Id}));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n");

WriteLiteral("\t\t\t\t");

            
            #line 44 "..\..\Views\Award\Index.cshtml"
           Write(Html.ActionLink("Delete", "Delete", new {id = item.Id}));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n");

            
            #line 47 "..\..\Views\Award\Index.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral("\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
